name: deploy
run-name: deploying view
on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/iron
      - run: npm ci
      - run: npm run build
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: dist/browser
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
