name: deploy
run-name: deploying view
on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build-project:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/iron
      - run: npm ci
      - run: npm run build
